[build]
  # Directory to change to before starting a build
  base = "."
  # Directory that contains the deploy-ready HTML files and assets
  publish = "dist"
  # Default build command
  command = "npm run build"

[build.environment]
  # Node.js version to use
  NODE_VERSION = "18"
  # Remove forced demo mode - let Firebase config determine mode
  # Set VITE_DEMO_MODE=false to force Firebase mode (requires Firebase env vars)
  VITE_DEMO_MODE = "false"

# Redirect rules for SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Handle API redirects to Netlify Functions if needed
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable" 